### ISSUE TITLE
Christiansen's monoid tactic

### ISSUE THREAD

**Issue by clayrat** [jdevuyst/rekenaar#1]
Could be useful for a reference: https://gist.github.com/david-christiansen/066ad771212b2f20ea40

**Comment by jdevuyst** [comment]
Ooh. `natPlusAsMonoid` looks interesting!

**Comment by jdevuyst** [comment]
Thanks @clayrat. That reference was very useful: https://github.com/jdevuyst/rekenaar/commit/51d0bab3b92bfb959774043e521453d082fbdcb7
